/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import PubModel.AbstractLandlord;
import PubModel.LandlordFactory;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;

/**
 *
 * @author jharrison12
 */
public class PubSimulatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form PubSimulatorGUI
     */
    public PubSimulatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDrinks = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbTap = new javax.swing.JRadioButton();
        rbBottle = new javax.swing.JRadioButton();
        rbCoffee = new javax.swing.JRadioButton();
        rbTea = new javax.swing.JRadioButton();
        rbCocktail = new javax.swing.JRadioButton();
        rbLongDrink = new javax.swing.JRadioButton();
        btnServeDrink = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Pub Simulator");

        buttonGroupDrinks.add(rbTap);
        rbTap.setText("Pint");
        rbTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTapActionPerformed(evt);
            }
        });

        buttonGroupDrinks.add(rbBottle);
        rbBottle.setText("Bottle");

        buttonGroupDrinks.add(rbCoffee);
        rbCoffee.setText("Coffee");

        buttonGroupDrinks.add(rbTea);
        rbTea.setText("Tea");

        buttonGroupDrinks.add(rbCocktail);
        rbCocktail.setText("Cocktail");

        buttonGroupDrinks.add(rbLongDrink);
        rbLongDrink.setText("Long Drink");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTap)
                    .addComponent(rbBottle)
                    .addComponent(rbCoffee)
                    .addComponent(rbTea)
                    .addComponent(rbCocktail)
                    .addComponent(rbLongDrink))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbTap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBottle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCoffee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCocktail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbLongDrink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnServeDrink.setText("ServeDrink");
        btnServeDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeDrinkActionPerformed(evt);
            }
        });

        TxtOutput.setColumns(20);
        TxtOutput.setRows(5);
        jScrollPane1.setViewportView(TxtOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnServeDrink)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnServeDrink)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTapActionPerformed

    public String getSelectedButtonText(ButtonGroup buttonGroupDrinks) {
        for (Enumeration<AbstractButton> buttons = buttonGroupDrinks.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;  
    }
    
    private void btnServeDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeDrinkActionPerformed
        String drink = getSelectedButtonText(buttonGroupDrinks);
        AbstractLandlord landlord;
        landlord = new LandlordFactory();      
        TxtOutput.setText(drink);
        landlord.setStrategy(LandlordFactory.selectStrategy(drink));
        drink = landlord.serveDrink();
        TxtOutput.setText(drink);
    }//GEN-LAST:event_btnServeDrinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PubSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PubSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PubSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PubSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PubSimulatorGUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtOutput;
    private javax.swing.JButton btnServeDrink;
    private javax.swing.ButtonGroup buttonGroupDrinks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbBottle;
    private javax.swing.JRadioButton rbCocktail;
    private javax.swing.JRadioButton rbCoffee;
    private javax.swing.JRadioButton rbLongDrink;
    private javax.swing.JRadioButton rbTap;
    private javax.swing.JRadioButton rbTea;
    // End of variables declaration//GEN-END:variables
}
