/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GuiView.SecretaryView;

import Controller.Medicines.MedicinesController;
import Controller.Medicines.MedicinesTemplate.DoctorRequestMedicineCreate;
import Controller.Medicines.MedicinesTemplate.SecretaryMedicineCreate;
import Model.Medicines.Medicine;
import Model.Medicines.MedicineList;
import Model.Users.Secretary;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class SecretaryAddStock extends javax.swing.JFrame {

    private Secretary secretary;
    /**
     * Creates new form SecretaryAddStock
     */
    public SecretaryAddStock() {
        initComponents();
        fillList();
    }
    
    public SecretaryAddStock(Secretary secretary) {
        initComponents();
        this.secretary = secretary;
        fillList();
    }

    private void fillList(){
        DefaultListModel listModelMedicine = new DefaultListModel();
        DefaultListModel listModelStock = new DefaultListModel();
        DefaultListModel listModelRequest = new DefaultListModel();
        MedicineList allMedicinesList = null;
        try {
            allMedicinesList = MedicinesController.getAllMedicines();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(SecretaryGiveMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<Medicine> allMedicines = allMedicinesList.getAllMedicines();
        if (allMedicines != null) {
            for (Medicine medicine : allMedicines) {
                listModelMedicine.addElement(medicine.getName());
                listModelStock.addElement(medicine.getQuantity());
            }
        }
        
        ArrayList<Medicine> requestMedicines = secretary.getRequestMedicines();
        if (requestMedicines != null) {
            for (Medicine medicine : requestMedicines){
                listModelRequest.addElement(medicine.getName());
            }
        }
        
        listMedicines.setModel(listModelMedicine);
        listAmount.setModel(listModelStock);
        listRequests.setModel(listModelRequest);
    }
    
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listMedicine = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listQuantity = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRequests = new javax.swing.JList<>();
        lblHome = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listMedicines = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtAmount1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listAmount = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(listMedicine);

        jScrollPane3.setViewportView(listQuantity);

        jLabel2.setText("Amount:");

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listRequests);

        lblHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHome.setText("Add Stock");

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Doctor Requests: ");

        jScrollPane5.setViewportView(listMedicines);

        jLabel3.setText("Amount:");

        txtAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmount1ActionPerformed(evt);
            }
        });

        jLabel4.setText("All Medicines:");

        jScrollPane6.setViewportView(listAmount);

        jLabel5.setText("Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHome)
                            .addComponent(jLabel1)
                            .addComponent(btnBack)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHome)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        String medicineName = listMedicines.getSelectedValue();
        MedicineList allMedicinesList = new MedicineList();
        String strAmount = txtAmount1.getText();
        boolean valid = true;
        int amount = 0;
        try{
            amount = Integer.parseInt(strAmount);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(new JFrame(), "Please select a valid amount(in integer)","Required input",JOptionPane.ERROR_MESSAGE);
            valid = false;
        }
        if (medicineName == null) {
            JOptionPane.showMessageDialog(new JFrame(), "Please select a medicine from the All medicines list","Required input",JOptionPane.ERROR_MESSAGE);
        }
        try {
            allMedicinesList = MedicinesController.getAllMedicines();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(SecretaryGiveMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<Medicine> requestMedicines = secretary.getRequestMedicines();
        ArrayList<Medicine> allMedicines = allMedicinesList.getAllMedicines();
        boolean isRequest = false;
        
        if (allMedicines != null && valid == true) {
            for (Medicine medicine : allMedicines) {
                if (medicine.getName().equals(medicineName)) {
                    int stock = medicine.getQuantity();
                    medicine.setQuantity(stock + amount);
                    if (requestMedicines!= null) {
                        for (Medicine reqMedicine : requestMedicines) {
                            if (reqMedicine.getName().equals(medicine.getName())) {
                                MedicinesController doctorRequestMedicine = new DoctorRequestMedicineCreate();
                                try {
                                    doctorRequestMedicine.addQuantity(secretary,medicine);
                                    isRequest = true;
                                } catch (IOException | ClassNotFoundException e) {
                                    e.printStackTrace();
                                }
                            }
                        } 
                    }                   
                    if (isRequest == false) {
                        MedicinesController secretaryMedicine = new SecretaryMedicineCreate();
                        try {
                            secretaryMedicine.addQuantity(secretary,medicine);
                        } catch (IOException | ClassNotFoundException e) {
                            e.printStackTrace();
                        }  
                    }
                }
            }
            fillList();
            JOptionPane.showMessageDialog(null, "Successfully added to stock", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new SecretaryView(secretary).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtAmount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmount1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryAddStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblHome;
    private javax.swing.JList<String> listAmount;
    private javax.swing.JList<String> listMedicine;
    private javax.swing.JList<String> listMedicines;
    private javax.swing.JList<String> listQuantity;
    private javax.swing.JList<String> listRequests;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAmount1;
    // End of variables declaration//GEN-END:variables
}
